# Makefile for gopy pkg generation of python bindings to cel-go
# File is generated by gopy (will not be overwritten though)
# gopy pkg https://github.com/google/cel-go

PYTHON=python
PIP=$(PYTHON) -m pip

all: gen

install: install-pkg install-exe

gen:
	gopy pkg https://github.com/google/cel-go

build:
	$(MAKE) -C cel-go build

install-pkg:
	# this does a local install of the package, building the sdist and then directly installing it
	rm -rf dist build */*.egg-info *.egg-info
	$(PYTHON) setup.py sdist
	$(PIP) install dist/*.tar.gz

install-exe:
	# install executable into /usr/local/bin
	cp cel-go/pycel-go /usr/local/bin/

