"""
Package ext contains CEL extension libraries where each library defines a related set of
constants, functions, macros, or other configuration settings which may not be covered by
the core CEL spec.

"""
# python wrapper for package github.com/google/cel-go/ext within overall package ext
# This is what you import to use the package.
# File is generated by gopy. Do not edit.
# gopy build -output=ext github.com/google/cel-go/ext

# the following is required to enable dlopen to open the _go.so file
import os,sys,inspect,collections
cwd = os.getcwd()
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
os.chdir(currentdir)
import _ext
os.chdir(cwd)

# to use this code in your end-user python file, import it as follows:
# from ext import ext
# and then refer to everything using ext. prefix
# packages imported by this package listed below:

import go



# ---- Types ---


#---- Constants from Go: Python can only ask that you please don't change these! ---


# ---- Global Variables: can only use functions to access ---


# ---- Interfaces ---


# ---- Structs ---


# ---- Slices ---


# ---- Maps ---


# ---- Constructors ---


# ---- Functions ---


